owner: yojoshb
repo: status

sites:
  - name: Plex
    url: $PLEX_URL
  - name: Ombi
    url: $OMBI_URL
  - name: Wiki
    url: $WIKI_URL
  - name: Valheim Server (Kingdom Kum)
    url: $VAL1
  - name: Valheim Server (Hall and Oaks)
    url: $VAL2
  - name: Minecraft Server
    url: $MC
  
status-website:
  cname: status.joshyb.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: dark
  name: JoshBs Service Monitor
  introTitle: "**Current Service(s) Status**"
  # introMessage: This status page queries **real-time** data using [Upptime](https://github.com/upptime/upptime).
  - title: Home
    href: /
  - title: GitHub
    href: https://github.com/$OWNER/$REPO
  
# https://upptime.js.org/docs/configuration
