owner: yojoshb
repo: status

sites:
  - name: Plex Media Server
    url: $URL_PLEX
  - name: Ombi
    url: $URL_OMBI
    icon: https://raw.githubusercontent.com/yojoshb/status/master/assets/ombi_icon.ico
  - name: Internal Wiki
    url: $URL_WIKI
  - name: Valheim Server (Kingdom Kum)
    url: $VAL1
  - name: Valheim Server (Hall and Oaks)
    url: $VAL2
  - name: Minecraft Server
    check: "tcp-ping"
    url: $MC
    port: $MC_PORT
  
status-website:
  cname: status.joshyb.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: dark
  name: Josh B's Service Monitor
  introTitle: "**Current Service(s) Status**"
  # introMessage: This status page queries **real-time** data using [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Home
      href: /
    - title: Plex Service Status
      href: https://plex.tv/
    - title: Ombi
      href: $OMBI_URL
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO
  
# https://upptime.js.org/docs/configuration
