owner: yojoshb
repo: status

sites:
  - name: Plex Media Server
    url: $URL_PLEX
    expectedStatusCodes: 
      - 401
    icon: https://raw.githubusercontent.com/yojoshb/status/master/assets/plex_icon.ico
  - name: Ombi
    url: $URL_OMBI
    icon: https://raw.githubusercontent.com/yojoshb/status/master/assets/ombi_icon.ico
  - name: Internal Wiki
    url: $URL_WIKI
    icon: https://raw.githubusercontent.com/yojoshb/status/master/assets/wiki_icon.ico
  - name: Valheim Server (Kingdom Kum)
    url: $VAL1
    icon: https://raw.githubusercontent.com/yojoshb/status/master/assets/valheim_icon.ico
  - name: Valheim Server (Hall and Oaks)
    url: $VAL2
    icon: https://raw.githubusercontent.com/yojoshb/status/master/assets/valheim_icon.ico
  - name: Minecraft Server
    #check: "tcp-ping"
    url: $MC
    #port: $MC_PORT
    # tcp-ping not reporting as failed when pings fail... so gonna put this guy in scheduled maintenance and fail it
    expectedStatusCodes: 
      - 401
    icon: https://raw.githubusercontent.com/yojoshb/status/master/assets/minecraft_icon.ico

assignees:
  - yojoshb
  
status-website:
  cname: status.joshyb.xyz
  # baseUrl: /your-repo-name
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://raw.githubusercontent.com/yojoshb/status/master/assets/pepe_thumbsup.png
  favicon: https://raw.githubusercontent.com/yojoshb/status/master/assets/pepe_thumbsup.png
  theme: dark
  name: Josh B's Status Page
  introTitle: "**Service Status**"
  introMessage: "**Real-time** data refreshed every ~5 minutes." 
  navbar:
    - title: Status
      href: /
    - title: Contact
      href: mailto:joshbezotte95@gmail.com
    - title: Git Repo
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
  
user-agent: yojoshb
  
# https://upptime.js.org/docs/configuration
