# Change these first
owner: yojoshb # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Ombi
    url: https://ombi.joshyb.xyz
  - name: Valheim Server
    url: https://valheim2.joshyb.xyz
  - name: Minecraft Server
    url: https://mc.joshyb.xyz
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.joshyb.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  js: "window.onload = function() { alert('Hello!') }"
  theme: dark
  name: Upptime
  introTitle: "**Current Service(s) Status**"
  introMessage: This is a status page which uses **real-time** data from [GitHub](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
