owner: yojoshb
repo: status

sites:
  - name: Plex Media Server
    url: $URL_PLEX
    expectedStatusCodes: 
      - 401
    icon: https://raw.githubusercontent.com/yojoshb/status/master/assets/plex_icon.ico
  - name: Ombi
    url: $URL_OMBI
    icon: https://raw.githubusercontent.com/yojoshb/status/master/assets/ombi_icon.ico
  #- name: Docs
    #url: $URL_WIKI
    #icon: https://raw.githubusercontent.com/yojoshb/status/master/assets/wiki_icon.ico
  - name: Vault
    url: $URL_VAULT
    icon: https://raw.githubusercontent.com/yojoshb/status/master/assets/vault_icon.ico
  - name: Guacamole
    url: $URL_GUAC
    icon: https://raw.githubusercontent.com/yojoshb/status/master/assets/guac_icon.ico
  - name: Valheim Server
    # waiting for proper udp-check or something to do this correctly
    check: "tcp-ping"
    port: 443
    url: $VAL1
    icon: https://raw.githubusercontent.com/yojoshb/status/master/assets/valheim_icon.ico
  #- name: Valheim Server (Great Hall and Oaks)
    #check: "tcp-ping"
    #port: 443
    #url: $VAL2
    #icon: https://raw.githubusercontent.com/yojoshb/status/master/assets/valheim_icon.ico
  #- name: Minecraft Server
    # tcp-ping not reporting as failed when pings fail... so gonna put this guy in scheduled maintenance and fail it
    #check: "tcp-ping"
    #url: $MC
    #port: $MC_PORT
    #icon: https://raw.githubusercontent.com/yojoshb/status/master/assets/minecraft_icon.ico

assignees:
  - yojoshb
  
status-website:
  cname: status.joshyb.xyz
  #baseUrl: /your-repo-name
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://raw.githubusercontent.com/yojoshb/status/master/assets/pepe_thumbsup.png
  favicon: https://raw.githubusercontent.com/yojoshb/status/master/assets/pepe_thumbsup.png
  theme: night
  name: Service Status
  #introTitle: "Status page for various services"
  #introMessage: "**Real-time** data refreshed every ~10 minutes" 
  navbar:
    - title: Status
      href: /
    #- title: Contact
    #  href: mailto:
    - title: Valheim Server Supervisor
      href: https://valsupervisor.joshyb.xyz/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
  
user-agent: yojoshb
  
# https://upptime.js.org/docs/configuration
