owner: yojoshb
repo: status

sites:
  - name: Plex
    url: $PLEX_URL
  - name: Ombi
    url: $OMBI_URL
  - name: Wiki
    url: $WIKI_URL
  - name: Valheim Server (Kingdom Kum)
    url: $VAL1
    status-website: Temporarily Disabled
  - name: Valheim Server (Hall and Oaks)
    url: $VAL2
  - name: Minecraft Server
    url: $MC
    status-website: Temporarily Disabled
  
status-website:
  cname: status.joshyb.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: dark
  name: JoshyBs Services Status
  introTitle: "**Current Service(s) Status**"
  introMessage: This status page uses **real-time** data from [GitHub](https://github.com/upptime/upptime). If you have any questions please contact me by email. [Gmail](mailto:joshbezotte95@gmail.com)
  navbar:
    - title: Home
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  metaTags:
    - name: "color-scheme"
      content: "dark light"

# https://upptime.js.org/docs/configuration
